# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QWidget


class Ui_Forms(QWidget):

    def setupUi(self, q_main_window):
        q_main_window.setObjectName("Form")
        q_main_window.resize(911, 688)
        self.horizontalLayoutWidget = QtWidgets.QWidget(q_main_window)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 861, 541))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidgetOldTable = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidgetOldTable.setObjectName("tabWidgetOldTable")
        self.tabOldSheet1 = QtWidgets.QWidget()
        self.tabOldSheet1.setObjectName("tabOldSheet1")
        self.tableWidget = QtWidgets.QTableWidget(self.tabOldSheet1)
        self.tableWidget.setGeometry(QtCore.QRect(10, 0, 381, 511))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidgetOldTable.addTab(self.tabOldSheet1, "")
        self.tabOldSheet2 = QtWidgets.QWidget()
        self.tabOldSheet2.setObjectName("tabOldSheet2")
        self.tabWidgetOldTable.addTab(self.tabOldSheet2, "")
        self.tabOldSheet3 = QtWidgets.QWidget()
        self.tabOldSheet3.setObjectName("tabOldSheet3")
        self.tabWidgetOldTable.addTab(self.tabOldSheet3, "")
        self.horizontalLayout.addWidget(self.tabWidgetOldTable)
        self.pushButtonDiff = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDiff.sizePolicy().hasHeightForWidth())
        self.pushButtonDiff.setSizePolicy(sizePolicy)
        self.pushButtonDiff.setObjectName("pushButtonDiff")
        self.horizontalLayout.addWidget(self.pushButtonDiff)
        self.tabWidgetNewTable = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidgetNewTable.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tabWidgetNewTable.setObjectName("tabWidgetNewTable")
        self.tabNewSheet1 = QtWidgets.QWidget()
        self.tabNewSheet1.setObjectName("tabNewSheet1")
        self.tabWidgetNewTable.addTab(self.tabNewSheet1, "")
        self.tabNewSheet2 = QtWidgets.QWidget()
        self.tabNewSheet2.setObjectName("tabNewSheet2")
        self.tabWidgetNewTable.addTab(self.tabNewSheet2, "")
        self.horizontalLayout.addWidget(self.tabWidgetNewTable)
        self.verticalLayoutWidget = QtWidgets.QWidget(q_main_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 861, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.pushButtonOldVersion = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonOldVersion.setObjectName("pushButtonOldVersion")
        self.horizontalLayout_2.addWidget(self.pushButtonOldVersion)
        #self.pushButtonOldVersion.clicked.connect(self.on_pushButtonOldVersion_clicked)

        self.textBrowserOldVersion = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowserOldVersion.setEnabled(True)
        self.textBrowserOldVersion.setMaximumSize(QtCore.QSize(746, 40))
        self.textBrowserOldVersion.setObjectName("textBrowserOldVersion")
        self.horizontalLayout_2.addWidget(self.textBrowserOldVersion)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonNewVesion = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonNewVesion.setObjectName("pushButtonNewVesion")
        self.horizontalLayout_3.addWidget(self.pushButtonNewVesion)
        self.textBrowserNewVesion = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowserNewVesion.setMaximumSize(QtCore.QSize(746, 40))
        self.textBrowserNewVesion.setObjectName("textBrowserNewVesion")
        self.horizontalLayout_3.addWidget(self.textBrowserNewVesion)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        # self.retranslateUi(Form)
        self.tabWidgetOldTable.setCurrentIndex(0)
        self.tabWidgetNewTable.setCurrentIndex(1)
        #self.pushButtonOldVersion.clicked.connect(self.textBrowserOldVersion.reload) # type: ignore
        #self.pushButtonNewVesion.clicked.connect(self.textBrowserNewVesion.reload) # type: ignore
        #self.pushButtonDiff.clicked.connect(self.tabWidgetOldTable.update) # type: ignore
        #.pushButtonDiff.clicked.connect(self.tabWidgetNewTable.update) # type: ignore
        # 确保按钮的对象名称与槽函数一致
        self.pushButtonOldVersion.setObjectName("pushButtonOldVersion")

        # 在 setupUi 方法的最后调用 connectSlotsByName
        QtCore.QMetaObject.connectSlotsByName(q_main_window)
        QtCore.QMetaObject.connectSlotsByName(self)

    @QtCore.pyqtSlot()
    def on_pushButtonOldVersion_clicked(self):
        print("click old version")
        #folder_path = QFileDialog.getExistingDirectory(self, "选择文件夹")
        #print("选择的文件夹路径：", folder_path)

    # def retranslateUi(self, Form):
    #     _translate = QtCore.QCoreApplication.translate
    #     Form.setWindowTitle(_translate("Form", "Form"))
    #     self.tabWidgetOldTable.setTabText(self.tabWidgetOldTable.indexOf(self.tabOldSheet1), _translate("Form", "sheet1"))
    #     self.tabWidgetOldTable.setTabText(self.tabWidgetOldTable.indexOf(self.tabOldSheet2), _translate("Form", "sheet2"))
    #     self.tabWidgetOldTable.setTabText(self.tabWidgetOldTable.indexOf(self.tabOldSheet3), _translate("Form", "sheet3"))
    #     self.pushButtonDiff.setText(_translate("Form", "diff"))
    #     self.tabWidgetNewTable.setWhatsThis(_translate("Form", "<html><head/><body><p>sheet1</p></body></html>"))
    #     self.tabWidgetNewTable.setTabText(self.tabWidgetNewTable.indexOf(self.tabNewSheet1), _translate("Form", "sheet1"))
    #     self.tabWidgetNewTable.setTabText(self.tabWidgetNewTable.indexOf(self.tabNewSheet2), _translate("Form", "sheet2"))
    #     self.pushButtonOldVersion.setText(_translate("Form", "old version"))
    #     self.pushButtonNewVesion.setText(_translate("Form", "new vesion"))

#slot


